### ISSUE TITLE
Select element does not coloring

### ISSUE THREAD

**Issue by erman999** [jgthms/bulma#3817] opened 2024-05-09 13:48 UTC
**Overview of the problem**
This is about the Bulma CSS framework
I'm using Bulma version [1.0.0]

**Description**
Coloring does not work for `select` elements. It does not even work in official website as well.
I tried with Chrome `124.0.6367.119`  also with Firefox `125.0.3`.
Result is the same for both of the browsers.

**Image of the issue**
<img width="788" alt="image" src="https://github.com/jgthms/bulma/assets/53808580/7a2d58a5-5946-4d3f-97e5-5b96b4deadd2">

**Expected behaviour of the element**
<img width="1009" alt="image" src="https://github.com/jgthms/bulma/assets/53808580/745d8431-a5d3-410e-a873-69ea63e89b25">

**Comment by veelci** [comment] 2024-05-13 17:36
This is a duplicate of #3755

**Comment by jrnvgt** [comment] 2024-05-27 13:51
This issue was fixed in version 1.0.1 and can be closed.

**Closed** 2024-06-04 10:21 UTC
