### ISSUE TITLE
Modal container does not cover full screan.

### ISSUE THREAD

**Issue by michalzwolinski** [jgthms/bulma#2278] opened 2018-12-11 08:03 UTC
This is about **.modal** overlay 

 I'm using Bulma **version** ```"bulma": "github:jgthms/bulma",```
My **browser** is: **Google Chrome** ```Version 70.0.3538.102 (Official Build) (64-bit)```

### Description

The modal component does not cover the entire surface of the screen when the viewport is smaller than page content. Scroll works for content under modal. When a user scrolls down modal goes up and reveals the rest of the content.

### Steps to Reproduce

1. Use .modal element
2. Add is-active 
3. Add more content then viewport height
4. Scroll down  

### Expected behavior

Just like https://bulma.io/documentation/components/modal/ i expect full coverage of the content and disabled browsers scroll func. Temporary i changed .modal rule ```position``` to ```fixed```

**Comment by mobayen** [comment] 2018-12-11 17:15
it works like a charm for me!
there might be your custom style that caused it

**Comment by mobayen** [comment] 2018-12-11 17:22
btw, I didn't find anything that Bulma suppose to disable browsers scroll functionality!!!

**Comment by michalzwolinski** [comment] 2018-12-12 07:41
https://bulma.io/documentation/components/modal/ - launch modal example and try scroll content under the modal container.

**Comment by mobayen** [comment] 2018-12-12 17:14
@michalzwolinski 
I did and also I have tried it on my machine!! but it works well at my end!
as I said before, likely it is other custom styles caused it

**Comment by ZiFFeL1992** [comment] 2018-12-18 09:28
I'm facing the same issue, it seems like a problem with overriding classes:

My web:
![image](https://user-images.githubusercontent.com/5492960/50144392-6a738a00-02af-11e9-92ac-1bdeb3f4b434.png)

Bulma.io:
![image](https://user-images.githubusercontent.com/5492960/50144458-9db61900-02af-11e9-8524-f9c0a4e94126.png)

**Comment by kornicameister** [comment] 2019-02-20 05:48
@ZiFFeL1992 let me check that.

**Comment by kornicameister** [comment] 2019-02-20 06:08
@ZiFFeL1992 I have the same situation as you do. I tried mangling around inside my source files, for instance I removed a lot of things trying to make so that only bulma is imported and some extensions. It didn't help. Removing extensions were also not an ok thing to do, since it didn't help as well.

**Comment by kornicameister** [comment] 2019-02-20 06:27
Can it because `.modal` uses `=overlay` mixin? I just noticed that this overlay acts quite weird. I am no expert, but it's pretty awkward that image is also using that in certain cases (i.e. `is-3by1`). For instance if I used that for a logo, it just went away outside of the viewport :/. However changing mixin to use `position: fixed` (which as far as I know seems more appropriate as element is position against the html root while `position: absolute` either position against the parent only if parent is positioned non statically, otherwise against the html root. That makes certain  gap here IMHO) makes an image reappear and modal is fixed as well.

**Comment by ZiFFeL1992** [comment] 2019-02-20 23:02
Check for duplicate imports, in your final build you might find that the mixins are built before the component, and therefore it gets overwritten..

**Comment by kornicameister** [comment] 2019-02-21 05:31
It got me thinking and I think you're right ;-).

I had this situation in codebase:

```typescript
import './Main.css'

import '@fortawesome/fontawesome-free/css/fontawesome.css';
import '@fortawesome/fontawesome-free/css/solid.css';
import '@fortawesome/fontawesome-free/css/brands.css';
import '@fortawesome/fontawesome-free/css/regular.css';
import 'font-linux/assets/font-linux.css';
```

Changing it to:

```typescript
import '@fortawesome/fontawesome-free/css/fontawesome.css';
import '@fortawesome/fontawesome-free/css/solid.css';
import '@fortawesome/fontawesome-free/css/brands.css';
import '@fortawesome/fontawesome-free/css/regular.css';
import 'font-linux/assets/font-linux.css';

import './Main.css'
```

i.e. moving `import ./Main.css` below fontawasome imports fixed the problem.

Fixed the issue. I cannot exactly explain it. Maybe something happening from interaction of `node-sass` and `create-elm-app`. Dunno ;-). Anyway, it works. Thx @ZiFFeL1992 for that suggestion.

**Comment by kornicameister** [comment] 2019-02-21 05:32
@jgthms would you mind closing it down, it seems that we managed to find a root cause which was a unwanted interaction between built css (that included bulma) and fontawasome related styles.

**Closed** 2019-05-17 11:02 UTC
