### ISSUE TITLE
X on notifs and buttons disfigured

### ISSUE THREAD

**Issue by chrislewispac** [jgthms/bulma#554] opened 2017-03-08 22:49 UTC
Most recent bulma version, see below. Occurs on ipad chrome.

![img_0237](https://cloud.githubusercontent.com/assets/10368004/23727795/88de30d6-0427-11e7-9dd8-71545c9f6fbd.PNG)

**Comment by robin900** [comment] 2017-03-09 01:17
Duplicate of #490 . There's a PR open, #549 , that fixes it.

If you need a workaround, edit the bulma sass files, or the bulma.css file, and add `padding: 0` to the selectors:

```
.tag .delete
.notification .delete
.message-header .delete
```

**Comment by jgthms** [comment] 2017-03-10 13:44
Duplicate

**Closed by jgthms** 2017-03-10 13:44 UTC
Labels: invalid or duplicate
