### ISSUE TITLE
Buttons using is-<info/success/warning/danger> and disabled are white in Safari 15.4

### ISSUE THREAD

**Issue by sysophost** [jgthms/bulma#3515] opened 2022-04-27 01:23 UTC
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.3
My **browser** is: Safari 15.4

### Description

Buttons that use the `disabled` attribute, in conjunction with `is-info`/`is-success`/`is-warning`/`is-danger` class are white (so invisible on a white background) but respond correctly when hovered.

Adding an additional class, such as `is-light`/`is-inverted` or removing the `is-success` class results in the disabled button being displayed as expected.

### Steps to Reproduce

1. Create a page with a disabled button. 

    ```html
    <html>
    <head>
	    <link rel="stylesheet" href="./bulma/css/bulma.css">
    </head>
    <body>
	    <button class="button is-success" disabled>Disabled button</button>
	    <button class="button is-success">Enabled button</button>
    </body>
    <html>
    ```

2. Render page in Safari
3. Observe disabled button is rendered in white 

### Expected behavior

Buttons using the `disabled` attribute, in conjunction with `is-success` class, should be rendered with the correct colouring but disabled

### Actual behavior

Buttons using the `disabled` attribute, in conjunction with `is-success` class, are white (so invisible on a white background)

**Comment by sysophost** [comment] 2022-04-27 01:23
This previously not an issue so is presumably related to a change in the latest version of Safari on macOS 12.3.1.

**Comment by nabedge** [comment] 2022-05-02 08:11
It is probably same issue for https://github.com/jgthms/bulma/issues/3500

**Comment by jgthms** [comment] 2022-05-07 09:07
Duplicate of #3500. Working on it now.

**Closed** 2022-05-08 13:10 UTC
