### ISSUE TITLE
Navbar dropdown link hard to focus when on the right

### ISSUE THREAD

**Issue by eman1986** [jgthms/bulma#974] opened 2017-07-30 22:31 UTC
This is about the Bulma **CSS framework
I'm using Bulma 0.5.0 
Using Chrome

### Description

I have a drop down link on my navbar thats setup to be on the right portion of the navbar, one minor issue I've noticed is that's its very hard to get focus of the dropdown list, it takes some mouse handywork to do it, I have not experience it with any other modes.

### Steps to Reproduce

1. Setup Navbar
2. Setup a dropdown for the right portion of the navbar
3. try to get to the list after its hovered

### Expected behavior

It lets you get to the dropdown links

### Actual behavior

it takes some work to get it to show up, most of the time the dropdown disappears after you mouse away from the parent link.

**Comment by jgthms** [comment] 2017-08-02 22:18
I believe it's a dupe of #866

**Closed by jgthms** 2017-08-02 22:18 UTC
