### ISSUE TITLE
Modal close icon on mobile

### ISSUE THREAD

**Issue by johnnymast** [jgthms/bulma#514] opened 2017-02-12 14:27 UTC
About: Bulma
IT's a: Bug

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.3.1
My **browser** is: iOS 10.3 Safari / iOS Chrome v?

### Description

The close modal icon on webkit related mobile browsers look off on iOS devices.

### Steps to Reproduce

On mobiel (could be iPad as well) fire up your browser and head over to http://bulma.io/documentation/components/modal/ and try out the **Modal card**  example.

### Expected behavior

The close button to look nice just like as on desktop.

### Actual behavior

This happends. Screenshot from iPhone 6.

![image](https://cloud.githubusercontent.com/assets/121194/22862895/b0c2ff80-f137-11e6-87e1-67887c96931f.png)

**Comment by alcovegan** [comment] 2017-02-12 17:07
Landed here for submit same issue.

Looked at http://bulma.io/documentation/elements/delete/ and same happened to me.
**Browsers:** iOS 10.1.1 Safari and Chrome.

![photo5262933847006357431](https://cloud.githubusercontent.com/assets/9094917/22864239/300f5188-f167-11e6-9543-c4bf952fb9d3.jpg)

**Comment by johnnymast** [comment] 2017-02-12 17:11
Good to see i am not alone.

**Comment by alcovegan** [comment] 2017-02-12 17:12
Looks like a same issue at #490

**Comment by johnnymast** [comment] 2017-02-12 17:13
Thats correct .. hmm sorry for the duplicate

**Comment by alcovegan** [comment] 2017-02-12 19:49
I found that removing `font-size: 1rem;` from class `.delete` can fix problem for `message-header` delete buttons, but not for `.tag` delete with `.is-small` class. Sorry, i'm not so good at debugging, but hope this might be helpful.

**Comment by johnnymast** [comment] 2017-02-12 19:55
Let me try

**Comment by xereda** [comment] 2017-02-24 17:20
How do I solve this?

**Comment by robin900** [comment] 2017-03-09 05:47
Duplicate of #490. PR #549 fixes it. @johnnymast that PR's comments describe an immediate workaround as well. @jgthms I think you can close this.

**Closed** 2017-03-15 22:17 UTC
Labels: bulma, is-bug
