### ISSUE TITLE
The last button in list of full-width buttons has longer width

### ISSUE THREAD

**Issue by SuperBo** [jgthms/bulma#1991] opened 2018-07-13 17:45 UTC
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.7.1]
My **browser** is: Opera

I am sure this issue is **not a duplicate**? Not sure!

### Description

The last button in the list of full-width buttons is longer when comparing to the rest.
<img width="500" alt="screen shot 2018-07-14 at 12 35 42 am" src="https://user-images.githubusercontent.com/2666479/42705770-a1e02e94-86fe-11e8-9f73-1a59562a940c.png">

### Steps to Reproduce

This error also occurs in the demo page of bulma.
[https://bulma.io/documentation/elements/button/#displays](https://bulma.io/documentation/elements/button/#displays)
### Expected behavior

The last button should have the same width as others in group.

### Actual behavior

The last button has longer width than others in group.

**Comment by willhoyle** [comment] 2018-07-21 21:07
Seems to be the following code found [here](https://github.com/jgthms/bulma/blob/740df6a0fa74383707e39b609dc46534d52c14a0/sass/elements/button.sass):

```
...

.buttons
  align-items: center
  display: flex
  flex-wrap: wrap
  justify-content: flex-start
  .button
    margin-bottom: 0.5rem
    &:not(:last-child)
      margin-right: 0.5rem

...
```

**Comment by jgthms** [comment] 2018-07-21 21:39
Yeah I use the “buttons” class in the docs for most examples.

It’s not a bug per se because it’s just for educational purposes. Here’s the only case where it’s not great because all buttons are full width.

**Comment by danielhep** [comment] 2018-08-29 01:04
I am encountering this. Did you guys just fix it with a custom CSS class? It's pretty annoying, but I understand why it exists. I think that fullwidth items should not have the margin on them.

**Comment by danielhep** [comment] 2018-08-29 01:05
Update: This can be fixed with the following.

```
.buttons .button:not(:last-child).is-fullwidth {
  margin-right: 0
}
```

**Comment by jgthms** [comment] 2018-09-04 13:18
```sass
&:not(:last-child):not(.is-fullwidth)
  margin-right: 0.5rem
```

should work.

**Comment by frederikhors** [comment] 2018-09-29 23:43
@jgthms are you adding this in the next release?

**Closed** 2018-10-02 05:51 UTC
Labels: bug, is-minor
