### ISSUE TITLE
File upload - Original button visible in Chrome latest version

### ISSUE THREAD

**Issue by mm98** [jgthms/bulma#1904] opened 2018-05-31 12:51 UTC
This is about **Bulma**.

it about Bulma
Is it a bug
If it's a bug, is it a browser bug? Yes

This is about the Bulma **CSS framework**
I'm using Bulma  **0.7.1**
My **browser** is: Google Chrome v67.0.3396.62 (win10)
I am sure this issue is **not a duplicate**? Yes (checked)

### Steps to Reproduce
It seams like a bug related to the latest Google Chrome. If you look at https://bulma.io/documentation/form/file/ you'll see that the original upload file button is visible ([sass](https://github.com/jgthms/bulma/blob/56d58280caa83689c3ccb8c549be2b36739bda71/sass/elements/form.sass#L354)). 

![Screenshot from latest Google Chrome](http://dev.roob.dk/bulma-file-upload.png)

### Expected behavior
Original form file/upload control should be hidden/invisible.

### Actual behavior
Original form file/upload control is visible.

**Comment by jgthms** [comment] 2018-05-31 13:37
Ugh it was the bug fix I merged yesterday. I knew something would break.

**Comment by mm98** [comment] 2018-05-31 13:43
Don't think so .. I haven't updated my local version and this shows the same problem. It works ok in FF and IE.

**Comment by jgthms** [comment] 2018-05-31 16:39
Are you on Linux? I can't reproduce:

![screen shot 2018-05-31 at 17 38 53](https://user-images.githubusercontent.com/1254808/40795298-88070816-64f9-11e8-955c-474d4e56a725.png)

**Comment by mm98** [comment] 2018-05-31 16:47
No, this is very odd. This started after i updated to the latest official Google Chrome **v67.0.3396.62** (64bit) without any extensions (released a couple of days ago) on Windows 10. I'll try to do some more debugging.

**Comment by mm98** [comment] 2018-06-01 06:36
This must be a specific Google Chrome on Windows problem. I just installed Chrome on another machine (clean machine), and the same happens:

<img width="421" alt="screenshot_1" src="https://user-images.githubusercontent.com/992714/40825088-d6b7edcc-6576-11e8-8a03-f7089f448fd1.png">

**Comment by eugestarr** [comment] 2018-06-18 00:20
Can confirm, using **Chrome** (67.0.3396.87) on **Mac OS X Sierra** (10.12.6):

![screen shot 2018-06-18 at 12 18 26](https://user-images.githubusercontent.com/13213650/41513507-c58ec466-72f1-11e8-98bd-85cf6bdf4bcd.png)

Why not just add `display: none` to `.file-input`?

**Comment by mm98** [comment] 2018-07-05 07:40
The file input can't be set to `display: none` i guess, since it will break a lot of third-party plugins like jquery validate. If the element is set to `display: none`, it won't get validated.

**Comment by mm98** [comment] 2018-07-05 15:19
It looks like css `height` and `width` has no effect on the button. This will only change the _textbox_ (lack of a better word) where the filename(s) is shown. Twitter Bootstrap uses `opacity: 0` on file inputs. This might be a good solution.

**Comment by viktorhbk** [comment] 2018-09-16 15:28
I'm having the same issue. 

Windows 10 Pro, v1803.
Chrome 68.0.3440.106 (Official Build) (64-bit)
The issue is also present in another somewhat popular webkit browser Opera v55.0.2994.44.

Can confirm that adding `opacity: 0` fixes the issue in both of them.

**Comment by net1957** [comment] 2018-09-24 17:13
would be nice if this can be added to the 7.2 release.
Thanks

**Closed** 2018-10-07 15:58 UTC
Labels: can't reproduce
