### ISSUE TITLE
SASS Version 3.5.1 compiles custom properties wrong

### ISSUE THREAD

**Issue by samuelmoser** [jgthms/bulma#1210] opened 2017-09-19 13:33 UTC
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.3]

This is a **Sass** issue: I'm using version 3.5.1

### Description
I'm a total noob and I'm not sure if it's a Sass or a Bulma misbehavior. With the newest Version of Sass 3.5.1 the columns.isVariable part compiles to

.columns.is-variable.is-1 {
  --columnGap: $ i *0.25px;
}
[...]

instead of (node-sass Version 3.5.0.beta.2)
.columns.is-variable.is-1 {
  --columnGap: 0.25px;
}
[...]

it's in the last part of columns.sass.

### Steps to Reproduce
Compile bulma with the newest Sass Version.

### Expected behavior
.columns.is-variable.is-1 {
  --columnGap: 0.25px;
}

### Actual behavior
.columns.is-variable.is-1 {
  --columnGap: $ i *0.25px;
}

**Comment by mofahead** [comment] 2017-11-03 04:03
Seeing this here on Sass 3.5.3. Pretty annoying, as a Rails app with up to date rails-sass gem will have this problem with Bulma and break the variable column gap functionality. 

Apparently this is correct behavior according to Sass from 3.5 going forward; custom property values are read as literal text, so anything dynamic needs to be surrounded by #{}.

Doesn't break currently using node-sass (tried with v3.8.0), but looks like this will change in the future ([see this discussion at LibSass](https://github.com/sass/libsass/issues/2076)). 

The fix for Bulma is easy, simply change the last line of columns.sass from
`      --columnGap: $i * 0.25rem`
to
`      --columnGap: #{$i * 0.25}rem`

I've patched mine and it now works on both sass and node-sass. =)

**Comment by mofahead** [comment] 2017-11-03 04:31
Turns out this is a dupe of [1283](https://github.com/jgthms/bulma/issues/1283), the only new info is that this affects Sass v3.5.

**Comment by jgthms** [comment] 2017-12-04 21:07
Works with Sass 3.5.3.

**Closed by jgthms** 2017-12-04 21:07 UTC
