### ISSUE TITLE
`select` class does not reliably update option selection when using `selected` attribute

### ISSUE THREAD

**Issue by rhigman** [jgthms/bulma#3524] opened 2022-05-11 14:18 UTC
This is a re-post of https://github.com/jgthms/bulma/issues/3390, which was closed due to inactivity, despite not having been addressed. The issue continues to impact users in production in multiple ways, e.g. https://github.com/thoth-pub/thoth/issues/321, https://github.com/thoth-pub/thoth/issues/366, https://github.com/thoth-pub/thoth/issues/372.

This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.9.1
My **browser** is: Firefox 90.0 (64-bit) and Chromium 92.0.4515.131 (Official Build) snap (64-bit) on Ubuntu 20.10

I am sure this issue is **not a duplicate**

### Description

Setting the `selected` attribute on an `<option>` of a `<select>` HTML element, using the Bulma `select` class, does not always cause the displayed selected option to change accordingly.

### Steps to Reproduce

1. Bring up a page containing an instance of the  `select` class which has `<options>`. (For example, https://bulma.io/documentation/form/select/.)
2. Using the browser developer tools, edit one of the `<option>` tags to contain a `selected` attribute, e.g. `<option selected="selected">`.
3. It may be necessary to repeat this a few times, moving the `selected` attribute to different options, before the bug is reproduced.

### Expected behavior

The option selected in the dropdown display changes to match the `<option>` with the `selected` attribute. (This is the behaviour when the same steps are performed on e.g. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select).

### Actual behavior

Initially, the actual behaviour may appear to match the expected behaviour. However, after a few repeats of the above steps, the displayed option selection no longer changes when the `selected` attribute is moved. As a result, the underlying value of the dropdown may become different from the value the user thinks it has. (An example of a user-raised issue resulting from this bug can be found here: https://github.com/thoth-pub/thoth/issues/228)

**Comment by jgthms** [comment] 2022-05-11 14:50
I am not able to reproduce this bug. If I set `selected="selected"` on an option, that options is displayed correctly.

Bulma is only styling the select, which means it is still behaving like the native select (with no styling). There is no JS involved. I'm not sure how Bulma's CSS could affect the behavior of the developer tools here?

**Comment by kauefr** [comment] 2022-05-11 20:26
+1 for Not Bulma Related.
The `.select` CSS class Bulma uses has nothing to do with the `selected` attribute of the option tag.
My best guess for what's causing your issue is something in your frontend framework, probably related to this (yewstack/yew#2530) issue.

**Comment by jgthms** [comment] 2022-05-11 20:43
I will close this now. I think it’s very unlikely Bulma is messing with the DOM behaviour like that.

**Closed by jgthms** 2022-05-11 20:43 UTC
