### ISSUE TITLE
On-Off Switch

### ISSUE THREAD

**Issue by mesqueeb** [jgthms/bulma#167] opened 2016-04-08 07:14 UTC
Something I feel is heavily used and needed in Bulma is an on-off switch.
Almost any user-settings page on websites can benefit for this, and after a quick google search I found out it was possible with only CSS.

I would like to suggest to integrate a switch OR maybe I can help writing it?
However I've never contributed on github before, so I'm not sure how. =S I'd love to try though.

**Comment by jgthms** [comment] 2016-04-08 08:53
This is a duplicate of #130

**Closed by jgthms** 2016-04-08 08:53 UTC
