### ISSUE TITLE
0.4.0 Nav menu has some problem

### ISSUE THREAD

**Issue by sausin** [jgthms/bulma#570] opened 2017-03-16 12:17 UTC
### Overview of the problem

The nav bar is behaving strangely now. 

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]
My **browser** is: Chromium 56

### Description

The right menu ends up closer to the center screen when resizing and there is a scrollbar that appears on the left menu

### Steps to Reproduce

1. Go to http://bulma.io/documentation/components/nav/
2. Resize the browser window
3. See the issue where 'is-tab' modifier is used in the nav

### Expected behavior

In the previous versions, this aligned correctly

### Actual behavior

It's aligning incorrectly

**Comment by jgthms** [comment] 2017-04-02 16:26
Probably dupe of #581

**Closed by jgthms** 2017-04-02 16:26 UTC
Labels: bulma, is-bug
