### ISSUE TITLE
Horizontal form with addons dont work

### ISSUE THREAD

**Issue by alexkleinubing** [jgthms/bulma#266] opened 2016-07-08 19:53 UTC
The code

```
<div class="control is-horizontal">
  <div class="control is-grouped">
    <p class="control has-addons is-expanded">
      <a class="button is-primary">X:</a>
      <input class="input" type="text" placeholder="Name">
    </p>
    <p class="control has-addons is-expanded">
      <a class="button is-primary">X:</a>
      <input class="input" type="email" placeholder="Email">
    </p>
  </div>
</div>   
```

Don't work as expected, I trying add some rules, but unsuccessfully.

https://i.imgsafe.org/0061b69ede.png

**Comment by jgthms** [comment] 2016-07-08 20:39
Dupe of #226

**Closed by jgthms** 2016-07-08 20:39 UTC
