### ISSUE TITLE
Way to configure stack orders

### ISSUE THREAD

**Issue by shigg1120** [jgthms/bulma#475] opened 2017-01-18 05:36 UTC
Is there any way to define stack orders on mobile?

For example, take a look at this

[https://jsbin.com/cipayeqepi/edit?html,output](https://jsbin.com/cipayeqepi/edit?html,output)

 It's horizontal on wide screens, when it shrinks "1" is on top.

How can I define an order to make "2" on top in this case.

I also tried to use `order`
[https://jsbin.com/yewifavoyo/edit?html,css,output](https://jsbin.com/yewifavoyo/edit?html,css,output)

**Comment by shigg1120** [comment] 2017-01-18 06:58
Thanks for the demo.I appreciate that.

But, I was wondering if I can achieve the same result **without** changing a html structure

**Comment by yoostk** [comment] 2017-01-18 07:12
Ah, OK. That would be something  like this?
You could write it cleaner using mixins though.

```html
<div class="columns reverse-row-order">
  <div class="column box">
    1
  </div>
  <div class="column box">  
    2
  </div>
</div>
```
```css
@media screen and (max-width: 769px) {
  .reverse-column-order {
    display: flex;
    flex-direction: column-reverse;
  }
}
```

https://jsbin.com/xovivuyome/edit?html,css,output

**Comment by shigg1120** [comment] 2017-01-18 07:21
That's perfect. Thanks alot.

Just out of curiosity, what if there are elements like this
~~~
<div class="columns reverse-row-order">
  <div class="column box">
    1
  </div>
  <div class="column box">  
    2
  </div>
  <div class="column box">  
    3
  </div>
  <div class="column box">  
    4
  </div>
</div>
~~~
and you want to order them like this on mobile

~~~
<div class="columns reverse-row-order">
  <div class="column box">
    3
  </div>
  <div class="column box">  
    2
  </div>
  <div class="column box">  
    1
  </div>
  <div class="column box">  
    4
  </div>
</div>
~~~
How would you do it?

**Comment by yoostk** [comment] 2017-01-18 07:41
Like this?

https://jsbin.com/dukihociyu/1/edit?html,css,output

And can you close the issue if you solved your question.

**Closed** 2017-01-18 07:45 UTC

**Comment by a-vilmin** [comment] 2019-02-05 02:06
FYI there's some major typos on this. Final code should be:
```
<div class="columns reverse-row-order">
  <div class="column box">
    2
  </div>
  <div class="column box">  
    1
  </div>
</div>
```

```
@media only screen and (min-width: 769px) {
  .reverse-row-order {
    display: flex;
    flex-direction: row-reverse;
  }
}
```

Just some inconsistent use of "row" and "column", as well as forgetting to reorder the columns in the markup. Works great tho!

**Comment by rajasimon** [comment] 2021-05-17 03:49
Is anyone want make this work I found `is-flex-direction-row-reverse` comes in handy. Although I only have two columns and I have to add it in reverse order and then in html it's magically display it in right order ( you can me weird ). Any how this is works in Bulma with flexbox ( I think from 0.9.1 ).

**Comment by drakon** [comment] 2021-05-19 19:28
> Is anyone want make this work I found `is-flex-direction-row-reverse` comes in handy. Although I only have two columns and I have to add it in reverse order and then in html it's magically display it in right order ( you can me weird ). Any how this is works in Bulma with flexbox ( I think from 0.9.1 ).

Yes, I also just tried that and it works. Strikes me as weird though. But then again I'm not too familiar with flexbox. Hopefully this is a feature and not a bug. :)

**Comment by deny7ko** [comment] 2021-07-09 06:34
Thanks @rajasimon 🙇

**Comment by ombudev** [comment] 2022-11-20 13:45
> Is anyone want make this work I found `is-flex-direction-row-reverse` comes in handy. Although I only have two columns and I have to add it in reverse order and then in html it's magically display it in right order ( you can call me weird ). Any how this is works in Bulma with flexbox ( I think from 0.9.1 ). 

I actually did this but it doesn't take effect on mobile but takes effect on desktop and the main effect it should take is on mobile and not desktop.
