### ISSUE TITLE
.tag breaks WordPress

### ISSUE THREAD

**Issue by LZDevs** [jgthms/bulma#3919] opened 2024-10-09 04:02 UTC
This is about **Bulma**.

Version: Bulma v1.0.2

Bug: Bulma brakes Tag archive in WordPress.

### Overview of the problem
Same as a previously closed issue: https://github.com/jgthms/bulma/issues/912

This is about the Bulma **CSS framework**

I'm using Bulma **version** 1.0.2

### Description
the WordPress adds .tag to the body class of tag archives, With Bulma CSS, the CSS structure ddoes not work.

### Steps to Reproduce

1. make a custom theme with bulma CSS.
2. Visit tag archive /tag/sample-tag

### Expected behavior
Should separate wordpress body tag class using .tag:not(body).

**Comment by LZDevs** [comment] 2024-10-09 04:07
Here is a hack I am using to get rid of the effect for now.
body.tag {
	background-color: initial;
	display: ;
	display: block;
	font-size: initial;
	white-space: initial;
	height: initial;
	padding: initial;
	color: var(--bulma-body-color);
	border-radius: initial;
}

**Comment by jgthms** [comment] 2024-10-18 11:48
Duplicate of #912

**Closed by jgthms** 2024-10-18 11:48 UTC
