### ISSUE TITLE
Suffix Button on Form Element Lacks Padding

### ISSUE THREAD

**Issue by kevinastone** [jgthms/bulma#29] opened 2016-01-31 16:41 UTC
In your example on your site, the Search button on the nav bar form is missing right padding (on Safari 9):
<img width="1095" alt="screenshot 2016-01-31 08 40 25" src="https://cloud.githubusercontent.com/assets/1234915/12703374/5c8f64e6-c7f6-11e5-8b4b-da295cbf5d54.png">

**Comment by richardkmichael** [comment] 2016-01-31 17:26
@kevinastone Dupe of #23, fixed with `flex-shrink: 0`.

**Closed** 2016-02-01 23:42 UTC
Labels: duplicate
