### ISSUE TITLE
CDN Links in Installation Docs Do Not Use Latest Release

### ISSUE THREAD

**Issue by joshkoppang** [jgthms/bulma#3840] opened 2024-06-12 19:10 UTC
This is about **the Docs**.

### Overview of the problem

The links under the CDN and Download sections in the installation documentation still refer to the 1.0.0 release, not the latest 1.0.1 release. https://bulma.io/documentation/start/installation/

This is about the Bulma **Docs**
 I'm using Bulma **version** [1.0.1] 

### Steps to Reproduce

Go to the Installation page of the docs, look at the URIs in CDN and the button/URI in the Download section.

### Expected behavior

Ability to use/download the latest release (1.0.1)

### Actual behavior

The documentation references the 1.0.0 release.

**Comment by jgthms** [comment] 2024-06-23 21:55
Duplicate of #3823

**Closed by jgthms** 2024-06-23 21:55 UTC
